import { BidOffer, CourierJob, Shipment } from "./types";

export const customerShipments: Shipment[] = [
  {
    id: 1001,
    jobNumber: "TX1001",
    title: "Textile cartons to Hamburg",
    origin: "Karachi, Pakistan",
    destination: "Hamburg, Germany",
    status: "Bidding",
    cargoMode: "Sea freight",
    courierMode: "Door to door",
    pickupDate: "May 13, 2026",
    eta: "May 27, 2026",
    amountRange: "PKR 1.2M - 1.6M",
    bids: 4,
    progress: 64,
    items: [
      {
        name: "Textile cartons",
        quantity: 24,
        weight: "1,180 kg",
        declaredValue: "PKR 1,750,000",
      },
    ],
  },
  {
    id: 1002,
    jobNumber: "TX1002",
    title: "Documents to Dubai",
    origin: "Lahore, Pakistan",
    destination: "Dubai, UAE",
    status: "Open",
    cargoMode: "Air freight",
    courierMode: "Warehouse pickup",
    pickupDate: "May 24, 2026",
    eta: "May 28, 2026",
    amountRange: "PKR 85K - 120K",
    bids: 0,
    progress: 28,
    items: [
      {
        name: "Trade documents",
        quantity: 2,
        weight: "3 kg",
        declaredValue: "PKR 25,000",
      },
    ],
  },
];

export const bidOffers: BidOffer[] = [
  {
    id: 501,
    courierName: "Maersk Logistics",
    label: "MAERSK ELBA - Voy 224W",
    total: "PKR 2.27M",
    route: "Karachi (KHI) -> Hamburg (HAM)",
    transitTime: "18 days",
    reliability: "92%",
    cutoff: "May 12 - 18:00",
    freeTime: "7 days",
    status: "Recommended",
  },
  {
    id: 502,
    courierName: "CMA CGM",
    label: "CMA CGM JACQUES SAADE - Voy 318W",
    total: "PKR 3.0M",
    route: "Karachi (KHI) -> Hamburg (HAM)",
    transitTime: "14 days",
    reliability: "96%",
    cutoff: "May 11 - 18:00",
    freeTime: "10 days",
    status: "Fastest",
  },
  {
    id: 503,
    courierName: "Hapag-Lloyd",
    label: "BERLIN EXPRESS - Voy 142E",
    total: "PKR 2.0M",
    route: "Karachi (KHI) -> Hamburg (HAM)",
    transitTime: "22 days",
    reliability: "78%",
    cutoff: "May 16 - 12:00",
    freeTime: "14 days",
    status: "Cheapest",
  },
];

export const courierJobs: CourierJob[] = [
  {
    id: 1001,
    jobNumber: "TX1001",
    customer: "Ayesha Khan",
    origin: "Karachi, Pakistan",
    destination: "Hamburg, Germany",
    status: "Bidding",
    cargo: "24 cartons - 1,180 kg",
    deadline: "6 days left",
    bidStatus: "Submitted",
    targetBudget: "PKR 1.2M - 1.6M",
  },
  {
    id: 1002,
    jobNumber: "TX1002",
    customer: "Hassan Imports",
    origin: "Lahore, Pakistan",
    destination: "Dubai, UAE",
    status: "Open",
    cargo: "2 document packs - 3 kg",
    deadline: "3 days left",
    bidStatus: "Not started",
    targetBudget: "PKR 85K - 120K",
  },
  {
    id: 1003,
    jobNumber: "TX1003",
    customer: "Memon Textiles",
    origin: "Karachi, Pakistan",
    destination: "Berlin, Germany",
    status: "Won",
    cargo: "1 40ft container",
    deadline: "Pickup tomorrow",
    bidStatus: "Accepted",
    targetBudget: "PKR 2.4M",
  },
];
