import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import { Provider } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
interface IProps {
  children: ReactNode;
}
export default function RootLayout({
  children,
}: IProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="container">
              {children}
          </div>
        </Provider>

      </body>
    </html>
  )
}
